<?php

/**
* Theme hook
*/
function contact_theme($existing, $type, $theme, $path) {
    return array(
        // Pages themes
        // ---------------------------------------------------------------------
        'custom_page' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'pages/custom'
        ),

        // Blocks themes
        // ---------------------------------------------------------------------
        'contact_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/contact'
        ),

        // Admins themes
        // ---------------------------------------------------------------------
        'contact_admin' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'admin/admin'
        ),
    );
}
