<?php

/**
* Theme hook
*/
function contact_theme($existing, $type, $theme, $path) {
    return array(
        // Pages themes
        // ---------------------------------------------------------------------
        'custom_page' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'pages/custom'
        ),

        // Blocks themes
        // ---------------------------------------------------------------------
        'contact_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/contact'
        ),

        // Admins themes
        // ---------------------------------------------------------------------
        'contact_admin' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'admin/admin'
        ),
    );
}


/**
* Mail hook
*/
function contact_mail($key, &$message, $params) {
    $options['langcode'] = $message['langcode'];
    switch($key) {
        case 'contact_us':
            $message['subject'] = t('Notification from amicolor');
            $message['body'][] = t("Dear is new content available on the site.");
        break;
    }
}
