<?php

/**
* Theme hook
*/
function sliders_theme($existing, $type, $theme, $path) {
    return array(
        // Pages themes
        // ---------------------------------------------------------------------

        // Blocks themes
        // ---------------------------------------------------------------------
        'sliders_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/sliders'
        ),

        // Admins themes
        // ---------------------------------------------------------------------
    );
}
