intro:
  who_we_are: "Amicolor est une société fondée par deux amis de longue date \r\nafin d’offrir des prestations dans le domaine de la peinture.\r\n\r\n<strong>Nicolas Herth</strong>\r\nResponsable clientèle\r\n\r\n<strong>Michael Notaro</strong>\r\nResponsable atelier"
  bio: "- peinture d’intérieur\r\n- peinture façades\r\n- crépi\r\n- volets\r\n- ferrures\r\n-giclage en atelier\r\n- boiseries\r\n- peinture des sols\r\n- barrières\r\n- escalier"
