<?php

/**
* Theme hook
*/
function layouts_theme($existing, $type, $theme, $path) {
    return array(
        // Pages themes
        // ---------------------------------------------------------------------

        // Blocks themes
        // ---------------------------------------------------------------------
        'layouts_header_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/header'
        ),
        'layouts_footer_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/footer'
        ),

        // Admins themes
        // ---------------------------------------------------------------------

    );
}
