<?php

/**
* Theme hook
*/
function contact_theme($existing, $type, $theme, $path) {
    return array(
        // Pages themes
        // ---------------------------------------------------------------------
        'custom_page' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'pages/custom'
        ),

        // Blocks themes
        // ---------------------------------------------------------------------
        'contact_block' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'blocks/contact'
        ),

        // Admins themes
        // ---------------------------------------------------------------------
        'contact_admin' => array(
            // Use the following syntax to retrieve all variables in the "variables" container
            'variables' => ['variables' => []],
            // Set the template attribute to force the theme suggestions into a sub folder
            // using [template].html.twig
            'template'  => 'admin/admin'
        ),
    );
}


/**
* Mail hook
*/
function contact_mail($key, &$message, $params) {
    $options['langcode'] = $message['langcode'];

    if( isset($params['from']) AND !empty($params['from']) ){
        $message['from'] = $params['from'];
    }

    switch($key) {
        case 'contact_us':

            $message['subject'] = t('Demande de contact depuis Amicolor.ch');
            $message['body'][] = t("Nouvelle demande de contact.");
            $message['body'][] = t("Nom: ") . $params['lastname'];
            $message['body'][] = t("Prénom: ") . $params['firstname'];
            $message['body'][] = t("Email: ") . $params['email'];
            $message['body'][] = t("Téléphone: ") . $params['phone'];
            $message['body'][] = t("Message: ");
            $message['body'][] = $params['message'];
        break;
    }
}
